### ISSUE TITLE
Add support for Forge servers

### ISSUE THREAD

**Issue by dkbednarczyk** [talwat/pap#7]
This was supposed to be a PR, but I wasn't able to finish what I started...
Instead of wasting that progress, I'll share what I found as an enhancement proposal instead:

- The recommended and latest versions of the Forge server by Minecraft version can be found [here](https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json), in JSON.
    - However, instead of a list, it's a large object, so to get the latest version without the user specifying a Minecraft version you can probably sort by keys
    - Same version list that `itzg/docker-minecraft-server` uses
- Forge JARs are named (roughly) as `(Minecraft version)-(Forge version)`-installer.jar`
    - Downloads are through their Maven repo, with a URL prefix of `https://maven.minecraftforge.net/net/minecraftforge/forge/`
    - Then, for example, to download a 1.19.3 server with version 44.1.23, append `(Minecraft version)-(Forge version)/forge-(Minecraft version)-(Forge version)-installer.jar` to the URL.

```go
// pseudo-go-code
prefix := "https://maven.minecraftforge.net/net/minecraftforge/forge"
mc := "1.19.3"
forge := forge.getLatestVersion()

fmt.Sprintf("%s/%s-%s/forge-%s-%s-installer.jar", prefix, mc, forge, mc, forge)
// https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.3-44.1.23/forge-1.19.3-44.1.23-installer.jar
```

- The installer JAR can install the server (optionally with a GUI, if no arguments are supplied) like so: `forge-installer.jar --installServer [dir]`, if a directory is not specified it uses the current directory.
    - After installing, the installer JAR is safe to remove
- `run.bat` and `run.sh` are generated in the installation directory
    - The server itself can be run at `./libraries/net/minecraftforge/forge/(MC version)-(Forge version)-server.jar`, but the convenience scripts load arguments in the same directory which are required for Forge to work

Setting up a Forge server is relatively similar to other servers, EULA, `server.properties`, mods and all.

**Comment by talwat** [comment]
I think this could be an interesting feature after pap v1.0.

**Comment by talwat** [comment]
How would this actually work with pap? Would pap just be in charge of downloading the installer?

**Comment by fooeyround** [comment]
Maybe implement an "install" step kind of like how plugins have, and it can run the installer in the main for for you? (Leave it in installer/ or something)


Could be a command line arg or a Y/N at runtime

**Comment by talwat** [comment]
That could be an option, or pap could just put a note saying something like "run the installer after"

**Comment by dkbednarczyk** [comment]
> How would this actually work with pap? Would pap just be in charge of downloading the installer?

Running the installer in a subprocess could work, as long as the machine has a Java executable in it's path (`javaw.exe`, `java.exe`)

**Comment by talwat** [comment]
At the same time, it wouldn't be too difficult for the user to just run it themselves, considering that they could still do everything from the command line, and this way it would work similarly to the other jars, but running it in a subprocess wouldn't be that bad since I already have functions in place to do this with pretty minimal code.

**Comment by talwat** [comment]
At the same time, it wouldn't be too difficult for the user to just run it themselves, considering that they could still do everything from the command line, and this way it would work similarly to the other jars, but running it in a subprocess wouldn't be that bad since I already have functions in place to do this with pretty minimal code.

**Comment by dkbednarczyk** [comment]
https://github.com/dxbednarczyk/forge-server
Minimum reproducible example of this being done with dependencies for version parsing, which can probably be reproduced using stdlib only but me lazy :P

**Comment by fooeyround** [comment]
Also could add an install feature and have pap make some file cache for jar name and information about if it has been installed, cleanable with another finish type command that would finalize multi step installs?

**Comment by dkbednarczyk** [comment]
> ...have pap make some file cache for jar name and information about if it has been installed

The Forge installer outputs a `.log` file during installation, in the same directory as the installer itself.

I think it would be best to save the output (often 20k lines+, best to gzip first) to [the user cache dir](https://pkg.go.dev/os#UserCacheDir) and have `pap` only parse the end of the log file, for example a successful install ends with 
```
The server installed successfully
You can delete this installer file now if you wish
```
and exits with code 0.

> ...cleanable with another finish type command that would finalize multi step installs

Would this also handle removal of the original installer, i.e. `--remove-installer`?
I assume you are talking along the lines of `pap clean`, etc. For me, it seems too ambiguous and many of its functionalities could just be handled with `pap download` and a flag (see above).

**Comment by talwat** [comment]
> Also could add an install feature and have pap make some file cache for jar name and information about if it has been installed, cleanable with another finish type command that would finalize multi step installs?

I feel like that might go a little beyond the scope of pap, but it could be a good feature. Although, I think it would likely only be useful for forge & fabric, which is why I would be hesitant on doing something like this.

Perhaps maybe after the install theres some kind of y/n option asking whether they want pap to run the installer?

**Comment by talwat** [comment]
> Could be a command line arg or a Y/N at runtime

Referring to this.
