### ISSUE TITLE
Generating install script assumes paper server

### ISSUE THREAD

**Issue by downj05** [talwat/pap#8]
Created a vanilla server (for new snapshot), install script generated with `pap sc` specified paper.jar, when it should have been `server.jar`

**Comment by talwat** [comment]
Yeah, this is a good point. I might actually make the --jar option mandatory to avoid users leaving it as default when that's usually not what they want.

**Comment by talwat** [comment]
I decided just to make it mandatory to avoid any issues if people use different jars.
