### ISSUE TITLE
Support for the Modrinth API

### ISSUE THREAD

**Issue by fooeyround** [talwat/pap#9]
The modrinth platform has support for mods **and** plugins, and can be used to fetch download links for jars and mod/plugin version information from provided modids , being the only thing that can change other than a rare api update (recently from v1 to v2) 

It could be its own subcommand eg: 
pap **modrinth** install mod fabric-api

**modrinth** may be omitted or shortened if you deem it appropriate, and it would be similar for plugins of course:

pap **modrinth** install plugin invsee 

Somewhat of the same code can be reused between them as they share many fields and attributes. Everything gets hosted on modrinth cdn (with uniform naming). 

This could also replace your static files all together, for config manipulation, you either could use a section for mods and their ids and a section for plugins and their ids. 
Modrinth can show information on loaders supported by mods (quilt support might help, but quilt is mostly like fabric) this could also be used to tell pap operators of incompatibilities, if also has "breaks" and dependencies fields. All of this with the filtering of client sided mods with the fields related to "side" support it would be a clean and great addition.

Also to note, you may also want to regex /config folder (using modid/pluginid and named to search) instead of keeping these static files holding their config locations, the only issue may be keeping track of if a mod/plugin used a folders or a lose file, but maybe it is smart to just try both and regex files ending in anything?
It is also optional to show the pap operator possible locations and making them confirm the ones to delete.

If this is unfeasible, it can be held with a file somewhat like before but just kept in two lists, one being plugin and one being mod. Each holding a dict of ids that have a dict each holding folder or file and the relative location, these could also be normally lists, allowing for the option to pass multiple files or folders, pap will load these and if no file is specified then keep track that the mod/plugin does not use it and vice versa for folder.

**Comment by fooeyround** [comment]
Hope you somewhat agree with these changes and think they are a good idea, I can't PR right now as I forgot to bring adequate development "gear" with me on an excursion (laptop).

**Comment by talwat** [comment]
This is actually already implemented in pap, and I should really make it known to the user. You use it by doing `pap plugin install modrinth:pluginslug`. I'll keep this issue open until I figure out a better way to communicate this feature.

**Comment by J0J0HA** [comment]
> by doing `pap plugin install modrinth:pluginslug`

I think it would be useful, if it would be possible to make a shourtcut for `pap pl gen b <name>` and `pap pl i <name>.json`, similar to the modrinth one you mentioned just for spigot, bukkti, etc., but I can understand if you prefer not to do that.

**Comment by talwat** [comment]
Not really sure what you are talking about, are you talking about the command itself or about shortening `modrinth` to `m` for example?

**Comment by talwat** [comment]
Also, [here](https://github.com/talwat/pap/issues/2) was the original issue that caused the feature to be already implemented

**Comment by fooeyround** [comment]
oh wow that is great!
